function[travel_times] = calculateTravelTime(ACCEPTED_POP, configID, linkMap, sensorMetaDataMap)

travel_times = zeros(size(ACCEPTED_POP(1).samples,2),2);

if mod(configID,2) == 1 && configID > 40
    travel_times(:,1) = linkMap(1).lengthInMiles ./ ACCEPTED_POP(1).samples(1,:) + ...
        linkMap(3).lengthInMiles ./ ACCEPTED_POP(3).samples(1,:) + ...
        sensorMetaDataMap(400739).offsetMiles ./ ACCEPTED_POP(5).samples(1,:);
    travel_times(:,2) = linkMap(1).lengthInMiles ./ ACCEPTED_POP(1).samples(1,:) + ...
        linkMap(3).lengthInMiles ./ ACCEPTED_POP(3).samples(1,:) + ...
        linkMap(5).lengthInMiles ./ ACCEPTED_POP(5).samples(1,:) + ...
        sensorMetaDataMap(400363).offsetMiles ./ ACCEPTED_POP(5).samples(1,:);
elseif mod(configID,2)== 0 && configID > 40
end
